/**
 * HKBTX 合约 ABI 定义
 */
export const DRG_ABI = [
  // ERC20标准
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function decimals() view returns (uint8)',
  'function totalSupply() view returns (uint256)',
  'function balanceOf(address account) view returns (uint256)',
  'function transfer(address to, uint256 amount) returns (bool)',
  'function transferFrom(address from, address to, uint256 amount) returns (bool)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function allowance(address owner, address spender) view returns (uint256)',
  // 铸造
  'function mint(address to, uint256 amount, string reason)',
  'function mintBatch(address[] tos, uint256[] amounts, string reason)',
  // 销毁
  'function burn(uint256 amount, string reason)',
  'function burnFrom(address account, uint256 amount, string reason)',
  // 产品信息
  'function getProductInfo() view returns (string name, string sku, uint256 priceCNY, uint256 servingDays)',
  'function setProductInfo(string name, string sku, uint256 priceCNY, uint256 servingDays)',
  // 角色
  'function MINTER_ROLE() view returns (bytes32)',
  'function BURNER_ROLE() view returns (bytes32)',
  // 事件
  'event Minted(address indexed to, uint256 amount, string reason)',
  'event Burned(address indexed from, uint256 amount, string reason)',
  'event ProductInfoUpdated(string name, string sku, uint256 priceCNY, uint256 servingDays)',
];

export const VAULT_ABI = [
  'function getQuote(uint256 usdtAmount) returns (tuple(uint256 usdtAmount, uint256 cnyAmount, uint256 rate, uint256 expiry, bool used))',
  'function payWithQuote(uint256 expectedUsdt)',
  'function directPay(uint256 usdtAmount)',
  'function getOracleRate() view returns (uint256)',
  'function operationalWallet() view returns (address)',
  'function distributor() view returns (address)',
  'function totalUsdtReceived() view returns (uint256)',
  'function totalOrders() view returns (uint256)',
  'event PaymentReceived(address indexed user, uint256 usdtAmount, uint256 cnyAmount, uint256 rate, uint256 operationalAmount, uint256 turboAmount)',
  'event QuoteCreated(address indexed user, uint256 usdtAmount, uint256 cnyAmount, uint256 rate, uint256 expiry)',
];

export const DISTRIBUTOR_ABI = [
  'function receiveFromVault(uint256 usdtAmount)',
  'function collectEarningTax(address user, uint256 usdtAmount)',
  'function totalUsdtCollected() view returns (uint256)',
  'function totalToReservePool() view returns (uint256)',
  'function totalToMint() view returns (uint256)',
  'function totalDrgMinted() view returns (uint256)',
  'function drgMintRate() view returns (uint256)',
  'event Distributed(uint256 indexed distributionId, uint256 usdtAmount, uint256 toPool, uint256 toMint)',
  'event DrgMinted(address indexed user, uint256 usdtAmount, uint256 drgAmount)',
];

export const RESERVE_POOL_ABI = [
  'function deposit(uint256 amount)',
  'function protectedWithdraw(address to, uint256 amount) returns (uint256)',
  'function emergencyWithdraw(uint256 amount)',
  'function getWithdrawableAmount(uint256 amount) view returns (uint256 finalAmount, bool isLinear)',
  'function totalPoolBalance() view returns (uint256)',
  'function totalInflow() view returns (uint256)',
  'function totalOutflow() view returns (uint256)',
  'function pendingReleaseAmount() view returns (uint256)',
  'function executeLinearRelease()',
  'event PoolDeposited(address indexed from, uint256 amount)',
  'event PoolWithdrawn(address indexed to, uint256 amount)',
  'event EmergencyWithdraw(address indexed user, uint256 amount, uint256 sequence)',
];

export const REWARD_ABI = [
  'function claim(uint256 index, address account, uint256 amount, bytes32[] merkleProof)',
  'function batchClaim(uint256[] indexes, address[] accounts, uint256[] amounts, bytes32[][] merkleProofs)',
  'function releaseFrozen()',
  'function hasClaimed(address) view returns (bool)',
  'function frozenBalance(address) view returns (uint256)',
  'function frozenUntil(address) view returns (uint256)',
  'function totalClaimed() view returns (uint256)',
  'function totalAirdropAmount() view returns (uint256)',
  'function canRelease(address) view returns (bool)',
  'function getRemainingFreezeTime(address) view returns (uint256)',
  'event Claimed(address indexed user, uint256 amount, uint256 freezeUntil, uint256 airdropId)',
  'event FreezeReleased(address indexed user, uint256 amount)',
];

export const TREE_ABI = [
  'function bindReferral(address referrer)',
  'function requestUnbound(address newReferrer, string reason)',
  'function executeUnbound()',
  'function cancelUnbound()',
  'function referrer(address) view returns (address)',
  'function getReferrals(address) view returns (address[])',
  'function getReferralCount(address) view returns (uint256)',
  'function referralCount(address) view returns (uint256)',
  'function treeDepth(address) view returns (uint256)',
  'function tierPoints(address) view returns (uint256)',
  'event ReferralBound(address indexed referrer, address indexed referee, uint256 timestamp)',
  'event UnboundExecuted(address indexed user, address indexed oldReferrer, address indexed newReferrer)',
];

export const STAKING_ABI = [
  'function stake(uint256 amount)',
  'function unstake(uint256 amount)',
  'function claimReward()',
  'function addReward(uint256 amount)',
  'function stakedAmount(address) view returns (uint256)',
  'function stakedAt(address) view returns (uint256)',
  'function totalStaked() view returns (uint256)',
  'function pendingRewards() view returns (uint256)',
  'function totalRewardsDistributed() view returns (uint256)',
  'function earnedReward(address) view returns (uint256)',
  'function getStakingInfo(address) view returns (uint256 staked, uint256 stakedSince, uint256 earned, uint256 lockEnd)',
  'function canUnstake(address) view returns (bool)',
  'function lockPeriod() view returns (uint256)',
  'event Staked(address indexed user, uint256 amount)',
  'event Unstaked(address indexed user, uint256 amount)',
  'event RewardClaimed(address indexed user, uint256 amount)',
  'event RewardAdded(uint256 amount, uint256 timestamp)',
];

export const HLTH_ABI = [
  // ERC20标准
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function decimals() view returns (uint8)',
  'function totalSupply() view returns (uint256)',
  'function balanceOf(address account) view returns (uint256)',
  'function transfer(address to, uint256 amount) returns (bool)',
  'function transferFrom(address from, address to, uint256 amount) returns (bool)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function allowance(address owner, address spender) view returns (uint256)',
  // 治理
  'function getVotes(address) view returns (uint256)',
  'function delegates(address) view returns (address)',
  'function delegate(address delegatee)',
  'function mint(address to, uint256 amount)',
  'function burnSelf(uint256 amount)',
  'function burnInactive(address user)',
  'function lastActivity(address) view returns (uint256)',
  'function DOMAIN_SEPARATOR() view returns (bytes32)',
  'function nonces(address) view returns (uint256)',
  'event InactivityBurned(address indexed user, uint256 amount, uint256 inactiveDays)',
];

export const TIMELOCK_ABI = [
  'function schedule(address target, uint256 value, bytes data, bytes32 predecessor, bytes32 salt, uint256 delay)',
  'function execute(address target, uint256 value, bytes data, bytes32 predecessor, bytes32 salt)',
  'function cancel(bytes32 id)',
  'function getMinDelay() view returns (uint256)',
  'function getProposalState(bytes32 id) view returns (uint8)',
  'function getProposalTimestamp(bytes32 id) view returns (uint256)',
  'event CallScheduled(bytes32 indexed id, uint256 indexed index, address target, uint256 value, bytes data, bytes32 predecessor, bytes32 salt, uint256 delay)',
  'event CallExecuted(bytes32 indexed id, uint256 indexed index, address target, uint256 value, bytes data)',
  'event Cancelled(bytes32 indexed id)',
  'event MinDelayChange(uint256 oldDuration, uint256 newDuration)',
];

export const DRG_REDEEM_ABI = [
  'function redeem(uint256 productId, uint256 quantity)',
  'function addProduct(string name, string sku, uint256 drgPrice, uint256 usdtPrice)',
  'function updateProduct(uint256 productId, string name, string sku, uint256 drgPrice, uint256 usdtPrice)',
  'function deactivateProduct(uint256 productId)',
  'function buybackBurn(uint256 usdtAmount, uint256 drgAmount)',
  'function directBurn(uint256 drgAmount)',
  'function getAllProducts() view returns (tuple(uint256 id, string name, string sku, uint256 drgPrice, uint256 usdtPrice, bool active)[])',
  'function getRedeemRecords(address) view returns (tuple(uint256 productId, uint256 drgAmount, uint256 usdtAmount, uint256 timestamp, bool fulfilled, uint256 nftTokenId)[])',
  'function totalRedeems() view returns (uint256)',
  'function totalDrgBurned() view returns (uint256)',
  'function totalUsdtUsedForBuyback() view returns (uint256)',
  'event Redeemed(address indexed user, uint256 productId, uint256 drgAmount, uint256 nftTokenId)',
  'event BuybackBurn(uint256 usdtAmount, uint256 drgAmount)',
  'event ProductAdded(uint256 indexed id, string name, uint256 drgPrice, uint256 usdtPrice)',
];

export const PRODUCT_NFT_ABI = [
  'function mint(address to, uint256 productId, uint256 quantity, bytes data) returns (uint256)',
  'function burn(uint256 tokenId, uint256 quantity)',
  'function balanceOf(address account, uint256 id) view returns (uint256)',
  'function uri(uint256 tokenId) view returns (string)',
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function totalSupply(uint256) view returns (uint256)',
  'function createProduct(string name, string description, string imageURI)',
  'event TransferSingle(address indexed operator, address indexed from, address indexed to, uint256 id, uint256 value)',
  'event TransferBatch(address indexed operator, address indexed from, address indexed to, uint256[] ids, uint256[] values)',
];

export const ZEDAO_ADAPTER_ABI = [
  'function swapDrgToZedao(uint256 drgAmount)',
  'function swapZedaoToDrg(uint256 zedaoAmount)',
  'function initiateCrossChain(uint256 amount, string targetChain, bytes additionalPayload)',
  'function completeCrossChain(bytes32 opId, bool success)',
  'function drgToZedaoRate() view returns (uint256)',
  'function zedaoToDrgRate() view returns (uint256)',
  'function getDrgBalance() view returns (uint256)',
  'function getZedaoBalance() view returns (uint256)',
  'function getRemainingDailyLimit() view returns (uint256)',
  'event DrgToZedaoSwapped(address indexed user, uint256 drgAmount, uint256 zedaoAmount)',
  'event ZedaoToDrgSwapped(address indexed user, uint256 zedaoAmount, uint256 drgAmount)',
  'event CrossChainInitiated(bytes32 indexed opId, address indexed user, uint256 amount, bool direction, string targetChain)',
];

// ============ New Contracts 2026-07-01 ============

export const TOKEN_HLTH_ABI = [
  // ERC20
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function decimals() view returns (uint8)',
  'function totalSupply() view returns (uint256)',
  'function balanceOf(address account) view returns (uint256)',
  'function transfer(address to, uint256 amount) returns (bool)',
  'function transferFrom(address from, address to, uint256 amount) returns (bool)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function mint(address to, uint256 amount)',
  'function burn(uint256 amount)',
  'function burnFrom(address account, uint256 amount)',
  'function MAX_SUPPLY() view returns (uint256)',
  'function INITIAL_SUPPLY() view returns (uint256)',
  'event Transfer(address indexed from, address indexed to, uint256 value)',
  'event Approval(address indexed owner, address indexed spender, uint256 value)',
];

export const TOKEN_DRG_ABI = [
  // ERC20
  'function name() view returns (string)',
  'function symbol() view returns (string)',
  'function decimals() view returns (uint8)',
  'function totalSupply() view returns (uint256)',
  'function balanceOf(address account) view returns (uint256)',
  'function transfer(address to, uint256 amount) returns (bool)',
  'function transferFrom(address from, address to, uint256 amount) returns (bool)',
  'function approve(address spender, uint256 amount) returns (bool)',
  'function allowance(address owner, address spender) view returns (uint256)',
  'function mint(address to, uint256 amount)',
  'function burn(uint256 amount)',
  'function burnFrom(address account, uint256 amount)',
  'function burnRate() view returns (uint256)',
  'function setBurnRate(uint256 _newRate)',
  'function totalBurned() view returns (uint256)',
  'function isExcluded(address account) view returns (bool)',
  'event Transfer(address indexed from, address indexed to, uint256 value)',
  'event Approval(address indexed owner, address indexed spender, uint256 value)',
];

export const REFERRAL_TREE_ABI = [
  'function registerReferral(address _referrer)',
  'function claimCommissions()',
  'function recordCommission(address _buyer, uint256 _amount)',
  'function distributeCommission(address _user, uint256 _amount)',
  'function isRegistered(address) view returns (bool)',
  'function referrer(address) view returns (address)',
  'function referrals(address, uint256) view returns (address)',
  'function getReferrals(address _user) view returns (address[])',
  'function getReferralChain(address _user) view returns (address[])',
  'function directReferralCount(address) view returns (uint256)',
  'function teamSize(address) view returns (uint256)',
  'function sbtLevel(address) view returns (uint256)',
  'function totalUsers() view returns (uint256)',
  'function totalCommissions(address) view returns (uint256)',
  'function pendingCommissions(address) view returns (uint256)',
  'function getTierInfo(address _user) view returns (uint256 level, string name, uint256 directCount, uint256 team)',
  'function setCommissionRates(uint256[3] _newRates)',
  'function setTierThresholds(uint256[5] _newThresholds)',
  'function batchUpdateLevels(address[] _users)',
  'function commissionRates(uint256) view returns (uint256)',
  'function tierThresholds(uint256) view returns (uint256)',
  'function tierNames(uint256) view returns (string)',
  'event ReferralRegistered(address indexed referrer, address indexed referee)',
  'event LevelUpdated(address indexed user, uint256 newLevel, string tierName)',
  'event CommissionRecorded(address indexed user, uint256 amount)',
  'event CommissionClaimed(address indexed user, uint256 amount)',
];

export const DAO_TREASURY_ABI = [
  'function createProposal(string _description, address[] _targets, uint256[] _values, bytes[] _calldatas)',
  'function vote(uint256 _proposalId, uint8 _choice)',
  'function executeProposal(uint256 _proposalId)',
  'function cancelProposal(uint256 _proposalId)',
  'function depositTreasury()',
  'function withdrawTreasury(address _to, uint256 _amount, string _reason)',
  'function sweepToken(address token, address to, uint256 amount)',
  'function getProposalCount() view returns (uint256)',
  'function proposalCount() view returns (uint256)',
  'function proposals(uint256) view returns (uint256 id, address proposer, string description, uint256 createdAt, uint256 voteStart, uint256 voteEnd, uint256 forVotes, uint256 againstVotes, uint256 abstainVotes, bool executed, bool cancelled, uint256 eta)',
  'function getProposal(uint256 _proposalId) view returns (tuple)',
  'function getProposalState(uint256 _proposalId) view returns (uint8)',
  'function voteChoice(uint256, address) view returns (uint8)',
  'function hasVoted(uint256, address) view returns (bool)',
  'function votePowerSnapshot(uint256, address) view returns (uint256)',
  'function getHasVoted(uint256 _proposalId, address _voter) view returns (bool)',
  'function treasuryETHBalance() view returns (uint256)',
  'function proposalThreshold() view returns (uint256)',
  'function setProposalThreshold(uint256 _newThreshold)',
  'function setTimelock(address _newTimelock)',
  'function hlthToken() view returns (address)',
  'function timelock() view returns (address)',
  'function QUORUM_PERCENTAGE() view returns (uint256)',
  'function VOTING_PERIOD() view returns (uint256)',
  'function PROPOSAL_DELAY() view returns (uint256)',
  'function GRACE_PERIOD() view returns (uint256)',
  'event ProposalCreated(uint256 indexed proposalId, address indexed proposer, string description, uint256 startTime, uint256 endTime)',
  'event VoteCast(uint256 indexed proposalId, address indexed voter, uint8 choice, uint256 power)',
  'event ProposalExecuted(uint256 indexed proposalId)',
  'event ProposalCancelled(uint256 indexed proposalId)',
  'event TreasuryDeposited(address indexed from, uint256 amount)',
  'event TreasuryWithdrawn(address indexed to, uint256 amount, string reason)',
];

export const DUAL_TURBINE_ABI = [
  'function distributeETH()',
  'function distributeToken(address _token, uint256 _amount)',
  'function distributionCount() view returns (uint256)',
  'function getDistributionRatio() view returns (uint256 reserve, uint256 staking)',
  'function getStats() view returns (uint256 totalETH, uint256 totalTokens, uint256 count, uint256 reservePct, uint256 stakingPct)',
  'function reservePool() view returns (address)',
  'function stakingRewards() view returns (address)',
  'function reserveRatio() view returns (uint256)',
  'function stakingRewardsRatio() view returns (uint256)',
  'function totalDistributedETH() view returns (uint256)',
  'function totalDistributedTokens() view returns (uint256)',
  'function setDistributionRatio(uint256 _reserveRatio, uint256 _stakingRewardsRatio)',
  'function setRecipients(address _reservePool, address _stakingRewards)',
  'function paused() view returns (bool)',
  'function setPaused(bool _paused)',
  'event DistributedETH(address indexed from, uint256 total, uint256 toReserve, uint256 toStaking)',
  'event DistributedToken(address indexed from, address indexed token, uint256 total, uint256 toReserve, uint256 toStaking)',
  'event RecipientsUpdated(address reservePool, address stakingRewards)',
  'event RatioUpdated(uint256 reserveRatio, uint256 stakingRatio)',
];
